### ISSUE TITLE
It looks like your use case is better supported by FluidLite

### ISSUE THREAD

**Issue by cpenny42** [VolcanoMobile/fluidsynth-android#1]
See here: [https://github.com/divideconcept/FluidLite](https://github.com/divideconcept/FluidLite)

I was porting fluidsynth to android (just like you're doing here), but it was such a headache! FluidLite is so much simpler, with essentially the exact same functionality.

**Comment by loki666** [comment]
except that FluidLite is 2 years old, and not updated with upstream
