### ISSUE TITLE
Cannot select instruments in certain sf2 files

### ISSUE THREAD

**Issue by davidedelvento** [VolcanoMobile/fluidsynth-android#10]
### FluidSynth version
Looks like the issue template is from upstream which I don't think applies "as is" to the Android version, trying to do my best.
This bug is for the latest Android FluidSynth MIDI (can't find a way to read the exact version in the GUI).

### Describe the bug
At least for some sf2 files, not all the instruments play correctly

### Expected behavior
All the content of an sf2 should be usable, or a clear error message should appear.

### Steps to reproduce
1. Download a sf2 file from https://sites.google.com/site/soundfonts4u/home for example the
**Extended Instrument Sets** ChateauGrand-Plus-Instruments-bs16i-v1.4   (479mb) 
https://drive.google.com/file/d/1hPZC5O_zO7klams_-hk-lnKTROFUdDvY/view?usp=sharing

2. Install said sf2 file in FluidSynth MIDI

3. Attempt to use it: only the first instrument (Chateau Grand) works, selecting any other instrument continues to play that first piano

### Additional context
I think I experienced a similar problem with one of the three downloadable SoundFonts (don't remember which one, #11 would have helped here), but in that case some instruments did not sound anything.

**Comment by loki666** [comment]
I'll look into this

**Comment by davidedelvento** [comment]
In case it helps to debug, on that page there are smaller sf2 files which also have the same problem, for example 
**Choir Voice**
Ooohs and Aaahs plus a solo voice with various presets with a nice clear sound.
KBH-Real-Choir-V2.5   (16.5mb)

**Comment by davidedelvento** [comment]
I found a workaround, and that is by sending MIDI program change. If the MIDI keyboard (e.g. as described in #12) sends a program change, that is correctly honored and it allows me to change the sound!

**Comment by loki666** [comment]
ok I think I know what's your issue, after selecting a preset in the drop down list, you still need to click the button "send" in the UI
let me know if it resolve your issue

**Comment by davidedelvento** [comment]
Doh! It does. As far as I am concerned, you may close this issue. Or perhaps keep it open if you want to change the UI to make it foolproof, since at least one fool fell in this trap.
Thanks!

**Comment by loki666** [comment]
Will be part of the redesign of the app
