### ISSUE TITLE
Remember history of loaded SoundFonts

### ISSUE THREAD

**Issue by davidedelvento** [VolcanoMobile/fluidsynth-android#11]
It would be nice if when selecting a new SoundFont to utilize, the old ones would not "forgotten" forever, but kept in a "recent" list in addition to the "select" and "download" option.

**Comment by loki666** [comment]
this will be addressed with presets management WIP for next update

**Comment by davidedelvento** [comment]
Fantastic, thanks.
Looking forward to it
