### ISSUE TITLE
Standalone mode

### ISSUE THREAD

**Issue by davidedelvento** [VolcanoMobile/fluidsynth-android#12]
It would be extremely nice for testing purposes if the app supported a standalone mode with on-screen keyboard so one would not have to hook-up a bulky MIDI device for example when debugging issues like #10

**Comment by loki666** [comment]
I don't think I want to go there with this application.
There are already other application you can install to connect to FluidSynth

**Comment by davidedelvento** [comment]
Thanks.

Your point is fair enough.

Can you please suggest any such application? The only one I found is a metronome, which is obviously not what is needed.

**Comment by loki666** [comment]
you can try https://play.google.com/store/apps/details?id=com.mobileer.midikeyboard

**Comment by davidedelvento** [comment]
For others who may read this and wonder: that app works like a charm, once you understand that you need to select FluidSynth in MIDIkeyboard (and **not** the other way around as you may suppose, which is what you need to do when connecting to an external MIDI hw).
