### ISSUE TITLE
Bug when playing notes outside of key range

### ISSUE THREAD

**Issue by batata004** [VolcanoMobile/fluidsynth-android#18]
This bug happens with any soundfont, is very simple to reproduce. Take a look at the screenshot below:

![image](https://github.com/FluidSynth/fluidsynth/assets/8988923/cfb6f3c9-d1a7-4739-ac20-b06441153445)

You can see I didnt specify a "Key range" to "Pad Amb 1" at the `PRESET`. However in the `INSTRUMENTS` panel I specified a "Key range", see print below:

![image](https://github.com/FluidSynth/fluidsynth/assets/8988923/a1a13fe7-01ed-4858-ace0-8f562a098bbd)

When this happens, FluidSynth (Android version) will not care about the "Key range" specified at the `INSTRUMENTS` panel. I need to explicitly set it ALSO at the PRESET panel. This is bad, because I will have to duplicate some information and keep track of it in at least 2 places.

If I set the "Key range" at the `PRESET` panel, it all works as expected. Using other apps like Audio Evolution, FL Studio, Cubasis... this bug does not happen and all of them use "Fluid Synth" library in their APKs. This is a bug specific to your app (version compiled by VolcanoMobile).

**Comment by batata004** [comment]
This bug was acknowledged by the Fluidsynth team at: https://github.com/FluidSynth/fluidsynth/issues/1250

They said they already fixed it, can you now recompile your app to include the new version without this bug?

**Comment by loki666** [comment]
yes, fix seems simple enough, I can probably backport it

**Comment by loki666** [comment]
spoke too soon, fix is simple, but this fork is so old, the patch doesn't apply correctly
I probably need to sync again with upstrem, and this is alot of work...

I'm not sure I'll fix it, but if you want to create a PR, you are very welcomed

**Comment by batata004** [comment]
@loki666 I am too dumb to compile an Android app. I already tried a least 4 or 5 times to customize some open source apps to my taste, but compiling it was frustating, never worked even after a few days seeking help.

Anyway, I have time left (my vacation ends in 2 weeks) so if you can point me in the right direction I can try to compile it with the new version of Fluidsynth and publish a PR here. I have nothing interesting to do in the next week, so I would be glad to help if I could!

As a side note, this app is amazing, many brazilian folks are using it. It's a huge success because it provides the best input lag possible! Not bloated with features, just the basics and works really great!

**Comment by loki666** [comment]
app v 2.0.28 update FluidSynth to v2.3.3 (includeing the fix for this issue)
