### ISSUE TITLE
How to use this library in Android Studio?

### ISSUE THREAD

**Issue by ghopretz** [VolcanoMobile/fluidsynth-android#2]
How to import and use this library in Android Studio?

**Comment by loki666** [comment]
you need something like this in your CMakeLists.txt

```
### INCLUDE FluidSynth LIBRARY ###

# Get the absolute path to the FluidSynth library directory
get_filename_component(FLUIDSYNTH_DIR
                       ${distribution_DIR}/fluidsynth-android
                       ABSOLUTE)

# Add the FluidSynth library as a subproject. Since FluidSynth is an out-of-tree source library we must also
# specify a binary directory
add_subdirectory(${FLUIDSYNTH_DIR}/android ./fluidsynth)
```

**Comment by ghopretz** [comment]
How to integrate this library with java language in android studio?

**Comment by ghopretz** [comment]
Can you give me example?

**Comment by loki666** [comment]
You need to write a JNI wrapper around the FluidSynth API you want to use in your application.
The JNI wrapper is not part of this project, and heavily depends on the applications needs

**Comment by lastant** [comment]
Could you please provide compiled *.so libraries for different platforms (maybe in the Assets section of releases) and a Java bindings file?

**Comment by lastant** [comment]
@loki666 I tried to use the built libraries from the MIDI Synthesizer app, I can see it has exported methods like initPlayback(), sendChannelEvent(), etc. But which parameters they accept is unclear.. It would be of course the best to see the full source code of the app ;), but at least the java binding file would be very helpful!

**Comment by lastant** [comment]
@ghopretz I used eventually the code from jOrgan, and it worked. For example, here is their JNI wrapper: https://sourceforge.net/p/jorgan/code/HEAD/tree/branches/jorgan-4.0/jorgan-fluidsynth/src/main/native/fluidsynthJNI.c

And here is their Java bindings file: https://sourceforge.net/p/jorgan/code/HEAD/tree/branches/jorgan-4.0/jorgan-fluidsynth/src/main/java/jorgan/fluidsynth/Fluidsynth.java

And here is the NDK sample project to put it all together: https://github.com/googlesamples/android-ndk/tree/master/hello-jni

**Comment by HectorRicardo** [comment]
Hello @lastant Any chance you have an example project ready to import to Android Studio ? I am still not sure how to generate the compiled *.so libraries. Thanks!
